### ISSUE TITLE
ModuleNotFoundError: No module named 'pascal_voc_writer'

### ISSUE THREAD

**Issue by gosha20777** [mukopikmin/bounding-box-augmentation#1]
what is the `pascal_voc_writer` module in `augment.py` file?
I've install imgaug package but when I've dunned the `augment.py` script I've get an error:

```
Traceback (most recent call last):
  File "augment.py", line 5, in <module>
    from pascal_voc_writer import Writer
ModuleNotFoundError: No module named 'pascal_voc_writer'
```

**Comment by gosha20777** [comment]
I've understand the dependencies. There is:
https://github.com/AndrewCarterUK/pascal-voc-writer

Thks!

**Comment by mukopikmin** [comment]
Thanks for comments.

In this repository, you can resolve dependencies with `pipenv`.
I recommend to use `pipenv` to install dependent packages.

https://pipenv-ja.readthedocs.io

Also dependencies are listed in `Pipenv.lock`.
