### ISSUE TITLE
augmented bounding-box may not be a rectangle

### ISSUE THREAD

**Issue by RunoobACMer** [mukopikmin/bounding-box-augmentation#11]
augmented bounding-box may not be a rectangle, like segment or point.
in this case, divided by (y_max - y_min) may cause "divide zero error".

**Comment by mukopikmin** [comment]
Sorry for my delayed response, I have been back to GitHub.

I think it is a corner case, but it is better if the case is considered.
Unfortunately, I am not maitaining this repo with a passion.
However, I welcome your contribution.
