### ISSUE TITLE
Any support for Oriented bounding boxes ?

### ISSUE THREAD

**Issue by shayan-NECX** [mukopikmin/bounding-box-augmentation#12]
Hi, thanks for your great work on this tool. I was wondering if there is any tool that augments **Oriented Bounding Box** images ? I am trying to use an annotation tool called roLabelImg which outputs xml file in PascalVOC format but i am not sure how to augment the images with their bounding boxes since its support is not present in this current tool.

If you know of any such tool, please let me know. Thanks.

**Comment by mukopikmin** [comment]
Unfortunately, I don't know such tools.
It is difficult to augument bounding boxes by orienting an image, because its aspect ratio will change when orienting it.
It seems to be achieved if the annotation is given by segmentation, but I think it is not a reasonable way.
