### ISSUE TITLE
The process kills by the system 

### ISSUE THREAD

**Issue by gosha20777** [mukopikmin/bounding-box-augmentation#2]
When I use your `augment.py` script I have bumped into the problem. My ubuntu kills the process -)

I wrote a simple script whitch restarts main prosess. I do not cureetelly know how you can fix it, so I stay this comment here to let you know about this prablem. 

Thank you for awsone tool)

**Comment by mukopikmin** [comment]
Sorry for my delayed response, I have been back to GitHub.

Unfortunately, I am not maitaining this repo with a passion.
However, I welcome your contribution.

Your comment made me happy, thx.
